version: '3'
services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    container_name: grafana
    user: "$UID:$GID"
    volumes:
      - /home/george/data/configs/grafana:/var/lib/grafana
      - /home/george/data/configs/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  loki:
    container_name: loki
    image: grafana/loki:2.5.0
    restart: unless-stopped
    ports:
      - 3100:3100
    volumes:
      - loki:/data/loki
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  promtail:
    container_name: promtail
    image: grafana/promtail:2.3.0
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /home/george/data/configs/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

volumes:
  loki:
