version: '3'
services:
  promtail:
    image: grafana/promtail:2.5.0
    container_name: promtail
    ports:
    - 7980:7980
    restart: unless-stopped
    volumes:
    - /home/ubuntu/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    - /home/ubuntu/nginx-proxy-manager/data/logs/:/var/log/nginx/
    command: -config.file=/etc/promtail/promtail-config.yaml
